FROM mcr.microsoft.com/devcontainers/base:jammy
RUN sudo apt-get update
RUN sudo apt-get --assume-yes install cmake
RUN sudo apt-get --assume-yes install clang lld llvm
RUN sudo apt-get --assume-yes install libclang-dev
